version: '3.7'
services:
  zipkin:
    image: openzipkin/zipkin
    hostname: zipkin
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.5GB'
    ports:
      - "9411:9411"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  grafana:
      image: grafana/grafana
      container_name: grafana
      ports:
        - 3000:3000
      restart: unless-stopped
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=grafana
      volumes:
        - ./grafana/datasources:/etc/grafana/provisioning/datasources
        - ./grafana/providers:/etc/grafana/provisioning/dashboards
        - ./grafana/dashboards:/var/lib/grafana/dashboards
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      ZIPKIN_URL: http://zipkin:9411/api/v2/spans
volumes:
  prom_data: