spring:
  application:
    name: challenge
  datasource:
    url: jdbc:h2:mem:challenge
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate.ddl-auto: update
  h2:
    console.enabled: true

server:
  servlet:
    contextPath: /api/seguros

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c
    baggage:
      enabled: true
    enabled: true
  zipkin.tracing.endpoint: http://localhost:9411/api/v2/spans
